CC=g++
CC2=gcc
LIBS=-fopenmp -lm
CFLAGS=-Wall 
CFLAGS2=-Wall -std=c99
	#$(CC) TP03.cpp -o TP03.exe $(CFLAGS)

main: 
	$(CC) generatorKadane.cpp -o generatorKadane.exe $(LIBS) $(CFLAGS)

clean :
	rm generatorKadane.exe
